gsap.registerPlugin(Draggable);
const a=gsap.utils.toArray(".it"),b=document.querySelector(".mq"),c=document.querySelector(".tr"),d=document.querySelector(".pt"),e=document.querySelector(".lv"),f=document.querySelector("#c"),g=f.getContext("2d"),h=document.querySelector(".if"),i=[0,570,1140,2340,2910,3480];
let j=Array(i.length).fill(!1),k=0;
f.width=1920,f.height=1080;
const l=4679,m=n=>`img/frm/${n.toString().padStart(5,"0")}.webp`;
let o=[],p={frame:0},q=l;
for(let n=0;n<l;n++){const r=new Image;r.onload=w,r.src=m(n),o.push(r)}
function s(){const n=document.querySelector(".ex.in");n.classList.contains("active")&&(k=j.findIndex(Boolean))}
function t(n){k!==i.length-1?(i[k+1]/l).toFixed(3)===n.toFixed(3)&&c.t1.progress(i[k]/l):"0"==n.toFixed(0)&&c.t1.progress(i[k]/l)}
function u(n){const r=document.querySelector(".ex.in");for(let s=0;s<i.length;s++){const v=i[s]/l,w=i[s+1]?i[s+1]/l:1;if(n>=v&&n<w){v1(s);break}}r.classList.contains("active")&&t(n)}
function v1(n){const r=document.querySelector(".ex.in");r.classList.contains("active")&&t(n),j[n]||(j.fill(!1),j[n]=!0,w1(n))}
function w1(n){const r=document.querySelectorAll(".it"),s=document.querySelectorAll(".i"+n),v=document.querySelector(".ex.in .tx"),w=[
"<p>London, England</p><span>2023</span><p>Data Desk provides NGOs, think tanks, and media outlets with investigative research and analysis on the global oil and gas sector. Their work has appeared in <i>The Washington Post, The Guardian, Bloomberg, and Le Monde.</i> For instance—identifiing sanctions-busting shipments of jet fuel to Myanmar.</p><p>I was brought in to design their identity, website, data visualizations, and documents, with the challenge of appealing to two audiences: one seeking scientific rigor, the other drawn to innovative philanthropic approaches.</p><p>The solution embraced a paradox at the heart of data: it captures concrete realities, yet its representation often feels abstract and intangible. This duality became the foundation of the visual concept, inspiring impossible geometry that conveys certainty through disambiguation, while adjustable columns in the layout allow readers to navigate the information according to their perspective. The typeface Inter was chosen for its modern clarity, while the wordmark—customized with inspiration from Akzidenz Grotesk—balances authority with subtle personality, resulting in a confident, logical, yet approachable visual voice that resonates across both audiences.</p>",
"<p>New York, USA</p><span>2024</span><p>Hunterbrook Media is a newsroom dedicated to uncovering under-reported stories and holding bad actors to account without ads or paywalls, instead funding its work through litigation partnerships and strategic investments through its financial arm based on its reporting. Their investigations have appeared in <i>The New Yorker, The Financial Times, POLITICO, The Wall Street Journal,</i> and more.</p><p>Hunterbrook needed a brand that reflected their mission—bringing visibility to under-reported stories and holding bad actors to account—while resonating with its core audience: portfolio managers who value urgency, credibility, and personality by way of subtle flare. I built the identity around a dark-to-light transition to symbolize this mission, paired with a condensed logotype inspired by Vignelli’s proposal for <i>The European Journal</i> to convey urgency and old-school credibility. An abbreviated, ticker-inspired mark nods to their financial focus and influence, while the impactful blue echoes the audience’s sense of style, bringing all elements together with clarity and focus.</p>",
"<p>London, England</p><span>2022</span><p>For a proposed rebrand of Sony Electronics, I explored a broader brand consolidation, aiming to bring coherence to the fragmented visual landscape across Sony’s sub-brands. I retained the original Sony logotype, honoring its legacy and global recognition, and focused on building a flexible system around it.</p><p>Rooted in Sony’s mission—“Fill the world with emotion, through the power of creativity and technology”—the identity balances these two forces. A perfect square anchors the system, symbolizing the precision and control of technology, while hand-painted forms—drawn from a Japanese artist breaking through constraint—represent the creative potential Sony’s products unlock. This idea is reinforced by dynamic fluid simulations that appear to burst from the products themselves. The color palette draws from the iconic Trinitron series, distilling its bold red, green, and blue into a modern reinterpretation. Within this system, Sony’s products become vessels: structured, intentional, and open, allowing creativity to flow through.</p>",
"<p>London, England</p><span>2022</span><p>While I was working at Stinsensqueeze, I helped produce the identity for a posthumous exhibition celebrating the life and legacy of Alber Elbaz—the iconic former creative director of Lanvin and founder of AZ Factory.</p><p>Elbaz was known for his playful spirit, distinctive presence, and commitment to a more inclusive and human-focused fashion industry. The visual language aimed to reflect these qualities with warmth and clarity.</p><p>The identity features bold, expressive colors drawn from Elbaz’s personal palette, a rounded, blocky typeface that subtly mirrors his form and character, and layers of collage and hand-drawn sketches inspired by his fashion illustrations. The result is an identity that feels personal, joyful, and true to the designer’s legacy.</p>",
"<p>London, England</p><span>2022</span>I lead a small team brought on to develop the identity for Middlesex University’s Degree Show, themed “Radical Creativity.” The exhibition spanned a wide range of disciplines—visual arts, performance, design, games and media—and the challenge lay in creating a system that could unify such diversity without flattening it.<br><br>To reflect this range, we gathered material from each course and developed our own image database. I then used a generative adversarial network (GAN) to generate an evolving set of images. I intentionally interrupted the training process once the outputs became abstract and amorphous—visual representations of “pure” creativity always changing. I then transitioned these images between each other creating morphed animations, symbolizing creativity as a living, shifting force. To anchor this visual fluidity, we paired the imagery with a brutalist geometric typeface—a structured counterbalance that gave the imagery both scaffolding and contrast.",
"<p>Multiple Locations</p><span>2022–25</span>This is a collection of select projects spanning different stages of my creative practice. It includes experimental interactive websites—taking the reader through my favorite passage from Carl Sagan, another exploring public perceptions of mental health medication—as well as my final major project, an identity system for children’s toys made from recycled pizza boxes.<br><br>More recently, I’ve explored laser-cut furniture design as a hands-on, material-focused hobby, extending my interest in function, form, and making."
];v.innerHTML=w[n],r.forEach(x=>x.classList.remove("active")),s.forEach(x=>x.classList.add("active"))}
function x1(){const n=document.querySelectorAll(".ex button"),r=document.querySelectorAll(".ex");n.forEach(x=>{x.addEventListener("click",function(){const y=this.parentElement.classList.contains("active");r.forEach(z=>z.classList.remove("active")),y||(this.parentElement.classList.add("active"),s())})})}
function y1(){for(let n=0;n<2;n++)c.appendChild(d.cloneNode(!0))}
function z1(){g.clearRect(0,0,f.width,f.height),g.drawImage(o[p.frame],0,0)}
let A=gsap.to(p,{frame:l-1,snap:"frame",ease:"none",paused:!0,onUpdate:z1});
c.t1=gsap.timeline({paused:!0,repeat:-1,onUpdate(){A.progress(this.progress()),u(this.progress())}}).to(".tr",{duration:l/30,x:d.offsetWidth*-1,ease:"none"});
const B=document.createElement("div");
B.style.backgroundColor="red",Draggable.create(B,{type:"x",trigger:c,onDragStart(){c.t1.pause()},onDrag(){let n=(this.x*-1)%d.offsetWidth;c.t1.progress(n/d.offsetWidth+(n<0?1:0))},onDragEnd(){c.t1.play(),s()},onPress(){gsap.set(this.target,{x:gsap.getProperty(c,"x")}),this.update()}});
function w(n){q--,this.onload=null;let r=Math.round((l-q)/l*100*4);r<=100&&(e.textContent=r+"%"),100==r&&(gsap.set(f,{autoAlpha:1}),gsap.to(".lc",{autoAlpha:0,onComplete:()=>c.t1.play()}))}
y1(),x1();